name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout

      uses: actions/checkout@v2

    - name: Deployment

      uses: appleboy/ssh-action@master

      with:

        host: ${{ secrets.SSH_HOST }}

        key: ${{ secrets.SSH_PRIVATE_KEY }}

        username: ${{ secrets.SSH_USERNAME }}

        script: |

          cd /var/www/html/demo

          git checkout -f 

          git pull

    # steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: sudo chown -R $USER:www-data storage
    - name: Directory Permissions
      run: sudo chown -R $USER:www-data bootstrap/cache
    - name: Directory Permissions
      run: chmod -R 775 storage 
    - name: Directory Permissions
      run: chmod -R 755 bootstrap/cache

    - name: Sandip
      run: echo "12345"
    - name: Baliram
      run: echo "12345"
    - name: Tawhare
      run: echo "12345"
