on:
  push:
    branches:
      - master


jobs:
  create-delelopment-artifacts:
    name: Create Development Artifacts
    run-on: ubuntu-latest
    steps: 
      uses: action/checkout@v2
      run: |
        npm i
        npm run prod